TAG_ORDER = [
    "Health",
    "Shared - Auth",
    "Shared - Auth Google",
    "Shared - Auth Apple",
    "Shared - Auth Telegram",
    "Shared - Profile",
    "Shared - Dictionaries",
    "Shared - Exercises",
    "Shared - Programs",
    "Shared - Sessions",
    "Shared - Billing",
    "Shared - Notifications",
    "Shared - FAQ",
    "Shared - Legal",
    "Shared - Support",
    "Coach - Profile",
    "Coach - Dashboard",
    "Coach - Clients",
    "Coach - Calendar",
    "Coach - Programs",
    "Client",
    "Client - Catalog",
    "Admin - Auth",
    "Admin - Profile",
    "Admin - Dashboard",
    "Admin - Dictionaries",
    "Admin - Coach",
    "Admin - Client",
    "Admin - Links",
    "Admin - Programs",
    "Admin - Exercises",
    "Admin - Billing",
    "Admin - FAQ",
    "Admin - Legal",
    "Admin - Tickets",
]

TAG_DESCRIPTIONS = {
    "Health": "Проверка доступности API и подключения к PostgreSQL.",
    "Shared - Auth": "Общая авторизация Coach и Client: регистрация, пароль, refresh, выход.",
    "Shared - Auth Google": "Вход через Firebase Google ID token или native Google ID token.",
    "Shared - Auth Apple": "Вход через Firebase Apple ID token или native Sign in with Apple.",
    "Shared - Auth Telegram": "Вход через бота: телефон или @username, код в личку, затем verify.",
    "Shared - Profile": "Профиль пользователя: имя, рост, аватар, устройства. Общее для обеих ролей.",
    "Shared - Dictionaries": "Справочники: уровень, цели, мышцы, оборудование, форматы.",
    "Shared - Exercises": "Каталог упражнений: публичные и пользовательские.",
    "Shared - Programs": "Каталог программ: фильтры, карточка, сохранение, копия, шаринг.",
    "Shared - Sessions": "Живая тренировка: старт, подходы, прошлый результат, завершение.",
    "Shared - Billing": "Тарифы, подписка, карта, платежи и mock-оплата. audience=pro_trainer | pro_client.",
    "Shared - Notifications": "Лента уведомлений, непрочитанные и настройки рассылок.",
    "Shared - FAQ": "Публичные статьи FAQ. audience=trainer | client | all.",
    "Shared - Legal": "Пользовательское соглашение и политика конфиденциальности.",
    "Shared - Support": "Обращения в поддержку от Coach или Client.",
    "Coach - Profile": "Кабинет тренера: био, специализации, цена, форматы.",
    "Coach - Dashboard": "Дашборд, отчёты и клиенты, требующие внимания.",
    "Coach - Clients": "Только Coach. Клиенты тренера: список, заявки, замеры, заметки, статистика. Не путать с тегом Client.",
    "Coach - Calendar": "Календарь тренера: события, no-show, старт сессии.",
    "Coach - Programs": "Свои программы тренера: правка, дни и упражнения дня.",
    "Client": "Только Client. Кабинет клиента: главная, замеры, фотопрогресс, заметки, история тренировок. Не путать с Coach - Clients.",
    "Client - Catalog": "Каталог тренеров, отзывы, закладки и заявка на сотрудничество.",
    "Admin - Auth": "Вход администратора, refresh и выход. Только роль admin.",
    "Admin - Profile": "Текущий администратор.",
    "Admin - Dashboard": "Сводка отдельно по Coach и Client, сессиям и подпискам.",
    "Admin - Dictionaries": "Справочники для админ-панели.",
    "Admin - Coach": "Пользователи-тренеры (роль trainer / Coach): список, карточка, верификация.",
    "Admin - Client": "Пользователи-клиенты (роль client / Client): список и карточка.",
    "Admin - Links": "Связи тренер–клиент.",
    "Admin - Programs": "Каталог программ: создание, правка, архив, дни и упражнения.",
    "Admin - Exercises": "Каталог упражнений: создание, правка, удаление.",
    "Admin - Billing": "Тарифы, платежи и подписки (pro_trainer и pro_client).",
    "Admin - FAQ": "Управление статьями FAQ. audience: all / trainer / client.",
    "Admin - Legal": "Редактор юридических документов.",
    "Admin - Tickets": "Обращения поддержки и смена статуса.",
}
